/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventsSlugRouteImport } from './routes/events_.$slug'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard.tickets'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRegistrationsRouteImport } from './routes/dashboard.registrations'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminEventsEditIdRouteImport } from './routes/admin.events.edit.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events_/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/dashboard/tickets',
  path: '/dashboard/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRegistrationsRoute = DashboardRegistrationsRouteImport.update({
  id: '/dashboard/registrations',
  path: '/dashboard/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/admin/events/',
  path: '/admin/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/admin/events/new',
  path: '/admin/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEditIdRoute = AdminEventsEditIdRouteImport.update({
  id: '/admin/events/edit/$id',
  path: '/admin/events/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/events/edit/$id': typeof AdminEventsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/events/edit/$id': typeof AdminEventsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registrations': typeof DashboardRegistrationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/events_/$slug': typeof EventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/events/edit/$id': typeof AdminEventsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/attendance'
    | '/admin/participants'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/profile'
    | '/dashboard/registrations'
    | '/dashboard/settings'
    | '/dashboard/tickets'
    | '/events/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/admin/events/new'
    | '/admin/events/'
    | '/admin/events/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/attendance'
    | '/admin/participants'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/profile'
    | '/dashboard/registrations'
    | '/dashboard/settings'
    | '/dashboard/tickets'
    | '/events/$slug'
    | '/admin'
    | '/dashboard'
    | '/admin/events/new'
    | '/admin/events'
    | '/admin/events/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/attendance'
    | '/admin/participants'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/profile'
    | '/dashboard/registrations'
    | '/dashboard/settings'
    | '/dashboard/tickets'
    | '/events_/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/admin/events/new'
    | '/admin/events/'
    | '/admin/events/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRegistrationsRoute: typeof DashboardRegistrationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminEventsEditIdRoute: typeof AdminEventsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$slug': {
      id: '/events_/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/dashboard/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/registrations': {
      id: '/dashboard/registrations'
      path: '/dashboard/registrations'
      fullPath: '/dashboard/registrations'
      preLoaderRoute: typeof DashboardRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/admin/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/edit/$id': {
      id: '/admin/events/edit/$id'
      path: '/admin/events/edit/$id'
      fullPath: '/admin/events/edit/$id'
      preLoaderRoute: typeof AdminEventsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRegistrationsRoute: DashboardRegistrationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTicketsRoute: DashboardTicketsRoute,
  EventsSlugRoute: EventsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminEventsEditIdRoute: AdminEventsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
